server:
  port: 8086
spring:
  application:
    name: pizza-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/pizzadb

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true